/**
 * Entry point for plugin based routes
 */
exports.init = function(app) {
    /**
     * API Calls
     */
    
    // POST authenticate
    app.post('/authenticate', authenticate);
    
    // POST refresh
    app.post('/refresh', refresh);
    
    // POST invalidate
    app.post('/refresh', invalidate);
    
    
    /**
     * Implementations
     * Notes:
     * - Profile Id's seem to be constant
     * - Client Id's seen to be generated by the game client (probably computer specific)
     * - 
     */
    
    // Authenticate
    // Receives: { agent : { name : Minecraft , version : 1 } , username : username , password : xxxxxxx , clientToken : XX... }
    // Responds: { accessToken : XX... , clientToken : XX... , selectedProfile : { id : XX... , name : username } , availableProfiles : [ { id : XX... , name : username , ... ] }
    function authenticate(request, response){
        
    }
    
    // Refresh 
    // Receives: { clientToken : XX... , accessToken : XX... }
    // Responds: { accessToken : XX... , clientToken : XX... , selectedProfile : { id : XX... , name : username } }
    function refresh(request, response){
        
    }
    
    // Invalidate
    // Receives: { accessToken : XX... , clientToken : XX... }
    // Responds: Nothing
    function invalidate(request, response){
        
    }
}